[package]
name = "tests-shared"
version = "0.1.0"
edition = "2024"

[dependencies]

hash-injector =  { path = "../lib", features = ["asserts", "adt-const-params", "injector-checks-finish", "injector-checks-same-flow"] }
